# Generated by Django 3.1.7 on 2021-04-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20210419_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
