# Generated by Django 3.1.7 on 2021-04-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20210428_1513'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addtocart',
            unique_together=set(),
        ),
    ]
