# Generated by Django 3.1.7 on 2021-07-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20210709_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery',
            field=models.CharField(default='FREE Delivery On First Order.', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(default='50 Item In Stock', max_length=200),
        ),
    ]
